# Project
version=3.4.1
java_version=21

mod_name=YungsBetterFortresses
mod_full_name=YUNG's Better Nether Fortresses
mod_id=betterfortresses
mod_author=YUNGNICKYOUNG
mod_description=A complete redesign of Minecraft's Nether Fortresses!
mod_credits=Thanks so much to all my patrons!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.betterfortresses
mc_version=1.21.11
mc_version_range=[1.21, 1.22)
mc_version_range_fabric=>=1.21.9

fabric_version=0.141.3+1.21.11
fabric_loader_version=0.18.4
loom_version=1.15-SNAPSHOT

parchment_minecraft=1.21.11
parchment_version=2025.12.20

yungsapi_version=5.4.0
cloth_config_version=21.11.153
modmenu_version=17.0.0-beta.2

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home
